In [1]:
import requests
import pandas as pd
import time

In [2]:
APP_ID = "67334a16"
APP_KEY = "e78c57fd6ccc53aefea40098e9026670"

In [3]:
def scrape_jobs(
    app_id,
    app_key,
    what,
    where="India",
    pages=10,
    results_per_page=50
):
    
    all_jobs = []

    for page in range(1, pages + 1):

        url = "https://api.adzuna.com/v1/api/jobs/in/search/{}".format(page)

        params = {
            "app_id": app_id,
            "app_key": app_key,
            "results_per_page": results_per_page,
            "what": what,
            "where": where,
            "content-type": "application/json"
        }

        response = requests.get(url, params=params, timeout=20)

        if response.status_code != 200:
            print(f"Page {page} failed: {response.status_code}")
            continue

        data = response.json()

        jobs = data.get("results", [])

        print(f"Page {page}: {len(jobs)} jobs collected")

        for job in jobs:

            all_jobs.append({
                "job_id": job.get("id"),
                "job_title": job.get("title"),
                "company": job.get("company", {}).get("display_name"),
                "location": job.get("location", {}).get("display_name"),
                "salary_min": job.get("salary_min"),
                "salary_max": job.get("salary_max"),
                "description": job.get("description"),
                "job_url": job.get("redirect_url"),
                "created": job.get("created")
            })

        time.sleep(1)

    return pd.DataFrame(all_jobs)

In [4]:
df_test = scrape_jobs(
    app_id=APP_ID,
    app_key=APP_KEY,
    what="Data Scientist",
    where="India",
    pages=2,
    results_per_page=20
)

Page 1: 20 jobs collected
Page 2: 20 jobs collected

In [5]:
df_test.head()

,job_id,job_title,company,location,salary_min,salary_max,description,job_url,created
0,5867270220,Data Scientist,EXL,India,None,None,Advanced Analytics & Data Science Execution: L...,https://www.adzuna.in/land/ad/5867270220?se=mk...,2026-09-02T21:46:18Z
1,5876010793,Data Scientist,Infosys Finacle,"Bangalore, Karnataka",None,None,Job Title: Data Scientist and Senior Data Scie...,https://www.adzuna.in/land/ad/5876010793?se=mk...,2026-09-09T00:59:08Z
2,5870857421,Data Scientist,Tata Consultancy Services,"Bangalore, Karnataka",None,None,TCS has been a great pioneer in feeding the fi...,https://www.adzuna.in/land/ad/5870857421?se=mk...,2026-09-04T22:28:36Z
3,5864436644,Data Scientist,Atain,India,None,None,Data Scientist Location: Remote – India Experi...,https://www.adzuna.in/land/ad/5864436644?se=mk...,2026-09-01T16:22:31Z
4,5864424453,Data Scientist,AB InBev GCC India,"Bangalore, Karnataka",None,None,Dreaming big is in our DNA. It’s who we are as...,https://www.adzuna.in/land/ad/5864424453?se=mk...,2026-09-01T16:20:22Z

In [6]:
df_test.shape

(40, 9)

In [7]:
roles = [
    # Data & AI
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "Data Engineer",
    "Business Analyst",
    "AI Engineer",
    "Business Intelligence Analyst",

    # Software Development
    "Software Developer",
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Web Developer",
    "Mobile App Developer",

    # Cloud & DevOps
    "Cloud Engineer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Cloud Architect",
    "System Administrator",

    # Cybersecurity
    "Cybersecurity Engineer",
    "Cybersecurity Analyst",
    "Information Security Analyst",
    "Security Engineer",

    # Specialized AI / Data
    "AI/ML Researcher",
    "NLP Engineer",
    "Computer Vision Engineer",
    "MLOps Engineer",
    "Data Architect",
    "Solutions Architect"
]

In [8]:
all_data = []
for role in roles:

    print(f"\nScraping: {role}")

    role_df = scrape_jobs(
        app_id=APP_ID,
        app_key=APP_KEY,
        what=role,
        where="India",
        pages=10,
        results_per_page=50
    )

    role_df["search_role"] = role
    all_data.append(role_df)

    time.sleep(2)
jobs_df = pd.concat(all_data, ignore_index=True)

Scraping: Data Scientist
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Data Analyst
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Machine Learning Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Data Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Business Analyst
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: AI Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Business Intelligence Analyst
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 20 jobs collected
Page 5: 0 jobs collected
Page 6: 0 jobs collected
Page 7: 0 jobs collected
Page 8: 0 jobs collected
Page 9: 0 jobs collected
Page 10: 0 jobs collected

Scraping: Software Developer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6 failed: 503
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9 failed: 503
Page 10: 50 jobs collected

Scraping: Software Engineer
Page 1: 50 jobs collected
Page 2 failed: 503
Page 3: 50 jobs collected
Page 4 failed: 503
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Frontend Developer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Backend Developer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Full Stack Developer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Web Developer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Mobile App Developer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Cloud Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: DevOps Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Site Reliability Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Cloud Architect
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: System Administrator
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Cybersecurity Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Cybersecurity Analyst
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 4 jobs collected
Page 4: 0 jobs collected
Page 5: 0 jobs collected
Page 6: 0 jobs collected
Page 7: 0 jobs collected
Page 8: 0 jobs collected
Page 9: 0 jobs collected
Page 10: 0 jobs collected

Scraping: Information Security Analyst
Page 1: 50 jobs collected
Page 2: 43 jobs collected
Page 3: 0 jobs collected
Page 4: 0 jobs collected
Page 5: 0 jobs collected
Page 6: 0 jobs collected
Page 7: 0 jobs collected
Page 8: 0 jobs collected
Page 9: 0 jobs collected
Page 10: 0 jobs collected

Scraping: Security Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: AI/ML Researcher
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 45 jobs collected
Page 5: 0 jobs collected
Page 6: 0 jobs collected
Page 7: 0 jobs collected
Page 8: 0 jobs collected
Page 9: 0 jobs collected
Page 10: 0 jobs collected

Scraping: NLP Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 10 jobs collected
Page 6: 0 jobs collected
Page 7: 0 jobs collected
Page 8: 0 jobs collected
Page 9: 0 jobs collected
Page 10: 0 jobs collected

Scraping: Computer Vision Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 25 jobs collected
Page 4: 0 jobs collected
Page 5: 0 jobs collected
Page 6: 0 jobs collected
Page 7: 0 jobs collected
Page 8: 0 jobs collected
Page 9: 0 jobs collected
Page 10: 0 jobs collected

Scraping: MLOps Engineer
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 48 jobs collected
Page 10: 0 jobs collected

Scraping: Data Architect
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

Scraping: Solutions Architect
Page 1: 50 jobs collected
Page 2: 50 jobs collected
Page 3: 50 jobs collected
Page 4: 50 jobs collected
Page 5: 50 jobs collected
Page 6: 50 jobs collected
Page 7: 50 jobs collected
Page 8: 50 jobs collected
Page 9: 50 jobs collected
Page 10: 50 jobs collected

/var/folders/d1/dh2cqpn53q78qb4gs2ydj0rr0000gn/T/ipykernel_3539/1742781849.py:22: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  jobs_df = pd.concat(all_data, ignore_index=True)

In [9]:
jobs_df.shape

(12145, 10)

In [10]:
jobs_df.head()

,job_id,job_title,company,location,salary_min,salary_max,description,job_url,created,search_role
0,5867270220,Data Scientist,EXL,India,NaN,NaN,Advanced Analytics & Data Science Execution: L...,https://www.adzuna.in/land/ad/5867270220?se=DN...,2026-09-02T21:46:18Z,Data Scientist
1,5876010793,Data Scientist,Infosys Finacle,"Bangalore, Karnataka",NaN,NaN,Job Title: Data Scientist and Senior Data Scie...,https://www.adzuna.in/land/ad/5876010793?se=DN...,2026-09-09T00:59:08Z,Data Scientist
2,5870857421,Data Scientist,Tata Consultancy Services,"Bangalore, Karnataka",NaN,NaN,TCS has been a great pioneer in feeding the fi...,https://www.adzuna.in/land/ad/5870857421?se=DN...,2026-09-04T22:28:36Z,Data Scientist
3,5864436644,Data Scientist,Atain,India,NaN,NaN,Data Scientist Location: Remote – India Experi...,https://www.adzuna.in/land/ad/5864436644?se=DN...,2026-09-01T16:22:31Z,Data Scientist
4,5864424453,Data Scientist,AB InBev GCC India,"Bangalore, Karnataka",NaN,NaN,Dreaming big is in our DNA. It’s who we are as...,https://www.adzuna.in/land/ad/5864424453?se=DN...,2026-09-01T16:20:22Z,Data Scientist

In [11]:
jobs_df.to_csv(
    "raw_jobs.csv",
    index=False
)

In [12]:
jobs_df["search_role"].value_counts()

search_role
Data Scientist                   500
Web Developer                    500
Data Architect                   500
Security Engineer                500
Cybersecurity Engineer           500
System Administrator             500
Cloud Architect                  500
Site Reliability Engineer        500
DevOps Engineer                  500
Data Analyst                     500
Mobile App Developer             500
Cloud Engineer                   500
Full Stack Developer             500
AI Engineer                      500
Machine Learning Engineer        500
Data Engineer                    500
Backend Developer                500
Business Analyst                 500
Solutions Architect              500
Frontend Developer               500
MLOps Engineer                   448
Software Developer               400
Software Engineer                400
NLP Engineer                     210
AI/ML Researcher                 195
Business Intelligence Analyst    170
Computer Vision Engineer         125
Cybersecurity Analyst            104
Information Security Analyst      93
Name: count, dtype: int64

In [13]:
role_counts = (
    jobs_df["search_role"]
    .value_counts()
    .sort_values(ascending=True)
)

print(role_counts.to_string())

search_role
Information Security Analyst      93
Cybersecurity Analyst            104
Computer Vision Engineer         125
Business Intelligence Analyst    170
AI/ML Researcher                 195
NLP Engineer                     210
Software Engineer                400
Software Developer               400
MLOps Engineer                   448
Frontend Developer               500
Solutions Architect              500
Business Analyst                 500
Backend Developer                500
Data Engineer                    500
Data Scientist                   500
Full Stack Developer             500
Cloud Engineer                   500
Mobile App Developer             500
Data Analyst                     500
DevOps Engineer                  500
Site Reliability Engineer        500
Cloud Architect                  500
System Administrator             500
Cybersecurity Engineer           500
Security Engineer                500
Data Architect                   500
Web Developer                    500
AI Engineer                      500
Machine Learning Engineer        500