# Data Loading & Exploration

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("data.xlsx")

In [3]:
df.head()

,OrderID,CustomerID,Restaurant,FoodItem,Quantity,OrderValue,TotalAmount,DeliveryTime_Minutes,CustomerRating,City,PaymentMethod,OrderDate
0,1,1229,Biryani House,Pizza,1,465.61,465.61,57,1,Delhi,UPI,2024-05-05
1,2,1224,Healthy Bowl,Wrap,4,96.53,386.12,42,5,Chennai,Cash,2024-02-17
2,3,1604,Taco Town,Salad,5,298.15,1490.75,10,2,Mumbai,Card,2024-08-17
3,4,1105,Pizza Point,Taco,2,191.96,383.92,34,1,Hyderabad,Card,2024-06-21
4,5,1550,Pizza Point,Wrap,3,499.71,1499.13,34,1,Delhi,Card,2024-08-23

In [4]:
df.tail()

,OrderID,CustomerID,Restaurant,FoodItem,Quantity,OrderValue,TotalAmount,DeliveryTime_Minutes,CustomerRating,City,PaymentMethod,OrderDate
2995,2996,1024,Sushi Spot,Sandwich,5,561.70,2808.50,24,3,Mumbai,Cash,2024-04-24
2996,2997,1792,Pizza Point,Burger,2,321.62,643.24,52,2,Chennai,UPI,2024-10-26
2997,2998,1738,Sushi Spot,Wrap,4,210.30,841.20,48,5,Chennai,Card,2024-05-02
2998,2999,1505,Pasta Place,Pasta,5,248.04,1240.20,47,5,Hyderabad,Cash,2024-06-25
2999,3000,1590,Burger Hub,Burger,5,474.97,2374.85,36,5,Mumbai,Cash,2024-04-05

In [5]:
df.shape

(3000, 12)

In [6]:
df.columns

Index(['OrderID', 'CustomerID', 'Restaurant', 'FoodItem', 'Quantity',
       'OrderValue', 'TotalAmount', 'DeliveryTime_Minutes', 'CustomerRating',
       'City', 'PaymentMethod', 'OrderDate'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   OrderID               3000 non-null   int64
 1   CustomerID            3000 non-null   int64
 2   Restaurant            3000 non-null   object
 3   FoodItem              3000 non-null   object
 4   Quantity              3000 non-null   int64
 5   OrderValue            3000 non-null   float64
 6   TotalAmount           3000 non-null   float64
 7   DeliveryTime_Minutes  3000 non-null   int64
 8   CustomerRating        3000 non-null   int64
 9   City                  3000 non-null   object
 10  PaymentMethod         3000 non-null   object
 11  OrderDate             3000 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 281.4+ KB

In [9]:
df.dtypes

OrderID                   int64
CustomerID                int64
Restaurant               object
FoodItem                 object
Quantity                  int64
OrderValue              float64
TotalAmount             float64
DeliveryTime_Minutes      int64
CustomerRating            int64
City                     object
PaymentMethod            object
OrderDate                object
dtype: object

In [10]:
df.describe()

,OrderID,CustomerID,Quantity,OrderValue,TotalAmount,DeliveryTime_Minutes,CustomerRating
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,1397.573000,2.994333,338.074453,1009.472437,34.916333,3.002333
std,866.169729,233.609663,1.421141,149.676468,680.124564,14.943285,1.405342
min,1.000000,1001.000000,1.000000,80.050000,80.050000,10.000000,1.000000
25%,750.750000,1187.000000,2.000000,209.707500,458.070000,22.000000,2.000000
50%,1500.500000,1392.500000,3.000000,335.030000,853.350000,35.000000,3.000000
75%,2250.250000,1604.000000,4.000000,467.722500,1465.052500,48.000000,4.000000
max,3000.000000,1800.000000,5.000000,599.990000,2997.850000,60.000000,5.000000

In [11]:
for column in df.columns:
    print(f"\n{column}:")
    print(df[column].value_counts())

OrderID:
OrderID
1       1
2004    1
1995    1
1996    1
1997    1
       ..
1003    1
1004    1
1005    1
1006    1
3000    1
Name: count, Length: 3000, dtype: int64

CustomerID:
CustomerID
1141    11
1130    11
1403    10
1134    10
1047     9
        ..
1499     1
1407     1
1316     1
1549     1
1607     1
Name: count, Length: 784, dtype: int64

Restaurant:
Restaurant
Healthy Bowl     328
Pizza Point      309
Grill Master     306
Biryani House    305
Veg Express      300
Cafe Delight     297
Sushi Spot       296
Taco Town        293
Pasta Place      293
Burger Hub       273
Name: count, dtype: int64

FoodItem:
FoodItem
Wrap        332
Biryani     332
Coffee      312
Sandwich    304
Sushi       298
Pizza       296
Salad       296
Burger      293
Taco        269
Pasta       268
Name: count, dtype: int64

Quantity:
Quantity
1    625
4    619
3    594
5    592
2    570
Name: count, dtype: int64

OrderValue:
OrderValue
490.59    3
139.51    2
585.27    2
459.70    2
551.80    2
         ..
428.55    1
152.93    1
358.02    1
172.53    1
474.97    1
Name: count, Length: 2923, dtype: int64

TotalAmount:
TotalAmount
373.96     3
1006.72    2
431.10     2
553.22     2
859.12     2
          ..
2841.80    1
623.56     1
1518.36    1
838.20     1
2374.85    1
Name: count, Length: 2966, dtype: int64

DeliveryTime_Minutes:
DeliveryTime_Minutes
16    73
60    72
26    71
59    70
52    69
11    68
48    68
23    67
33    67
36    66
54    66
58    65
18    65
40    65
22    65
46    64
10    62
30    61
38    60
19    60
44    60
13    60
41    60
39    59
35    59
21    58
29    58
12    58
43    57
17    57
24    57
14    56
57    56
53    56
32    56
28    55
15    54
55    54
20    54
34    53
56    53
50    53
27    52
42    52
51    52
31    50
47    49
37    48
45    46
25    43
49    41
Name: count, dtype: int64

CustomerRating:
CustomerRating
4    627
3    605
1    595
2    592
5    581
Name: count, dtype: int64

City:
City
Delhi        629
Mumbai       619
Chennai      595
Hyderabad    594
Bangalore    563
Name: count, dtype: int64

PaymentMethod:
PaymentMethod
UPI     1050
Cash     987
Card     963
Name: count, dtype: int64

OrderDate:
OrderDate
2024-07-10    19
2024-02-17    18
2024-04-05    18
2024-10-09    16
2024-05-01    15
              ..
2024-10-15     2
2024-12-20     2
2024-09-20     1
2024-11-01     1
2024-03-24     1
Name: count, Length: 364, dtype: int64

In [12]:
print("\nTotal Orders:", df["OrderID"].nunique())
print("Unique Customers:", df["CustomerID"].nunique())
print("Unique Restaurants:", df["Restaurant"].nunique())

print("\nOrders by City:")
print(df["City"].value_counts())

Total Orders: 3000
Unique Customers: 784
Unique Restaurants: 10

Orders by City:
City
Delhi        629
Mumbai       619
Chennai      595
Hyderabad    594
Bangalore    563
Name: count, dtype: int64

# Data Cleaning & Preparation

In [13]:
df.isnull().sum()

OrderID                 0
CustomerID              0
Restaurant              0
FoodItem                0
Quantity                0
OrderValue              0
TotalAmount             0
DeliveryTime_Minutes    0
CustomerRating          0
City                    0
PaymentMethod           0
OrderDate               0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
print("\nInvalid Quantity:")
print(df[df["Quantity"] <= 0])

Invalid Quantity:
Empty DataFrame
Columns: [OrderID, CustomerID, Restaurant, FoodItem, Quantity, OrderValue, TotalAmount, DeliveryTime_Minutes, CustomerRating, City, PaymentMethod, OrderDate]
Index: []

In [16]:
print("\nInvalid OrderValue:")
print(df[df["OrderValue"] < 0])

Invalid OrderValue:
Empty DataFrame
Columns: [OrderID, CustomerID, Restaurant, FoodItem, Quantity, OrderValue, TotalAmount, DeliveryTime_Minutes, CustomerRating, City, PaymentMethod, OrderDate]
Index: []

In [ ]:
print("\nInvalid TotalAmount:")
print(df[df["TotalAmount"] < 0])

Invalid TotalAmount:
Empty DataFrame
Columns: [OrderID, CustomerID, Restaurant, FoodItem, Quantity, OrderValue, TotalAmount, DeliveryTime_Minutes, CustomerRating, City, PaymentMethod, OrderDate]
Index: []

In [18]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors="coerce")

In [19]:
df["Year"] = df["OrderDate"].dt.year
df["Month"] = df["OrderDate"].dt.month
df["Weekday"] = df["OrderDate"].dt.day_name()

In [21]:
print("\nUpdated Dataset:")
print(df.head())

Updated Dataset:
   OrderID  CustomerID     Restaurant FoodItem  Quantity  OrderValue  \
0        1        1229  Biryani House    Pizza         1      465.61
1        2        1224   Healthy Bowl     Wrap         4       96.53
2        3        1604      Taco Town    Salad         5      298.15
3        4        1105    Pizza Point     Taco         2      191.96
4        5        1550    Pizza Point     Wrap         3      499.71

   TotalAmount  DeliveryTime_Minutes  CustomerRating       City PaymentMethod  \
0       465.61                    57               1      Delhi           UPI
1       386.12                    42               5    Chennai          Cash
2      1490.75                    10               2     Mumbai          Card
3       383.92                    34               1  Hyderabad          Card
4      1499.13                    34               1      Delhi          Card

   OrderDate  Year  Month   Weekday
0 2024-05-05  2024      5    Sunday
1 2024-02-17  2024      2  Saturday
2 2024-08-17  2024      8  Saturday
3 2024-06-21  2024      6    Friday
4 2024-08-23  2024      8    Friday

In [22]:
print("\nUpdated Data Types:")
print(df.dtypes)

Updated Data Types:
OrderID                          int64
CustomerID                       int64
Restaurant                      object
FoodItem                        object
Quantity                         int64
OrderValue                     float64
TotalAmount                    float64
DeliveryTime_Minutes             int64
CustomerRating                   int64
City                            object
PaymentMethod                   object
OrderDate               datetime64[ns]
Year                             int32
Month                            int32
Weekday                         object
dtype: object

# Exploratory Data Analysis

In [23]:
food_revenue = (
    df.groupby("FoodItem")["TotalAmount"]
    .sum()
    .sort_values(ascending=False)
)

print("Top Food Items by Revenue:")
display(food_revenue.head(10))

Top Food Items by Revenue:

FoodItem
Wrap        337200.28
Biryani     325413.15
Sandwich    314966.84
Coffee      312958.93
Pizza       308228.32
Salad       306190.67
Burger      304492.51
Sushi       289492.34
Taco        264892.06
Pasta       264582.21
Name: TotalAmount, dtype: float64

In [24]:
restaurant_revenue = (
    df.groupby("Restaurant")["TotalAmount"]
    .sum()
    .sort_values(ascending=False)
)

print("Top Restaurants:")
display(restaurant_revenue.head(10))

Top Restaurants:

Restaurant
Healthy Bowl     327202.56
Grill Master     316202.87
Veg Express      315967.22
Pizza Point      315815.32
Cafe Delight     302825.20
Sushi Spot       296465.45
Taco Town        292171.78
Biryani House    290586.02
Pasta Place      289554.91
Burger Hub       281625.98
Name: TotalAmount, dtype: float64

In [25]:
customer_revenue = (
    df.groupby("CustomerID")["TotalAmount"]
    .sum()
    .sort_values(ascending=False)
)

print("Top Customers:")
display(customer_revenue.head(10))

Top Customers:

CustomerID
1141    14134.08
1695    13501.95
1595    12656.74
1092    11249.61
1774    10878.03
1792    10851.75
1117    10767.46
1394    10762.00
1403    10651.21
1004    10603.11
Name: TotalAmount, dtype: float64

In [26]:
city_revenue = (
    df.groupby("City")["TotalAmount"]
    .sum()
    .sort_values(ascending=False)
)

print("Revenue by City:")
display(city_revenue)

Revenue by City:

City
Delhi        661013.09
Mumbai       611626.51
Hyderabad    606399.53
Chennai      581559.79
Bangalore    567818.39
Name: TotalAmount, dtype: float64

In [28]:
payment_distribution = df["PaymentMethod"].value_counts()
payment_distribution

PaymentMethod
UPI     1050
Cash     987
Card     963
Name: count, dtype: int64

In [29]:
rating_distribution = df["CustomerRating"].value_counts().sort_index()
rating_distribution

CustomerRating
1    595
2    592
3    605
4    627
5    581
Name: count, dtype: int64

In [30]:
print("\nAverage Customer Rating:", df["CustomerRating"].mean())

Average Customer Rating: 3.0023333333333335